### ISSUE TITLE
genSourcesDecompile fails to decompile 2 classes

### ISSUE THREAD

**Issue by Derailedzack** [minecraft-cursed-legacy/Example-Mod#9]
> Task :genSourcesDecompile
Error thrown whilst in com/jcraft/jorbis/Floor1/jorbis/FuncTime
Method inverse1 (Lcom/jcraft/jorbis/Block;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; couldn't be decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.exps.FunctionExprent.checkExprTypeBounds(FunctionExprent.java:386)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:139)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:124)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:124)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.lambda$processVarTypes$1(VarTypeProcessor.java:118)
        at org.jetbrains.java.decompiler.modules.decompiler.sforms.DirectGraph.iterateExprents(DirectGraph.java:98)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.processVarTypes(VarTypeProcessor.java:118)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.calculateVarTypes(VarTypeProcessor.java:44)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarVersionsProcessor.setVarVersions(VarVersionsProcessor.java:44)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarProcessor.setVarVersions(VarProcessor.java:37)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:148)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:61)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:444)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:380)
        at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:148)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error thrown whilst in net/minecraft/client/Minecraft
Method method_2130 (Ljava/lang/String;)V couldn't be decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.util.VBStyleCollection.removeWithKey(VBStyleCollection.java:88)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractIfBlock(LoopExtractHelper.java:197)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractFirstIf(LoopExtractHelper.java:160)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoop(LoopExtractHelper.java:85)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:54)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoops(LoopExtractHelper.java:20)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:162)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:61)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:444)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:380)
        at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:148)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error thrown whilst in net/minecraft/class_477
Method getWorkingDirectory (Ljava/lang/String;)Ljava/io/File; couldn't be written.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplify(SwitchHelper.java:29)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SwitchStatement.toJava(SwitchStatement.java:109)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:766)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:110)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:24)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:835)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:273)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:398)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:161)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:200)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error thrown whilst in net/minecraft/client/Minecraft
Method getWorkingDirectory (Ljava/lang/String;)Ljava/io/File; couldn't be written.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplify(SwitchHelper.java:29)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SwitchStatement.toJava(SwitchStatement.java:109)
        at org.jetbrains.java.decompiler.modules.decompiler.ExprProcessor.jmpWrapper(ExprProcessor.java:766)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SequenceStatement.toJava(SequenceStatement.java:110)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:24)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:835)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:273)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:398)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:161)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:200)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error thrown whilst in net/minecraft/client/options/GameOptions
Method getBooleanValue (Lnet/minecraft/client/options/Option;)Z couldn't be written.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.SwitchHelper.simplify(SwitchHelper.java:29)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.SwitchStatement.toJava(SwitchStatement.java:109)
        at org.jetbrains.java.decompiler.modules.decompiler.stats.RootStatement.toJava(RootStatement.java:24)
        at org.jetbrains.java.decompiler.main.ClassWriter.methodToJava(ClassWriter.java:835)
        at org.jetbrains.java.decompiler.main.ClassWriter.classToJava(ClassWriter.java:273)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:398)
        at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:161)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$3(ContextUnit.java:200)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Derailedzack** [comment]
```
> Configure project :
Fabric Loom: 0.2.7-SNAPSHOT Build(Sin▓ 0d0261a)
:setting up loom dependencies
:providing org.checkerframework:checker-qual:2.8.1
:providing org.ow2.asm:asm-tree:8.0
:providing com.google.errorprone:error_prone_annotations:2.3.2
:providing com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
:providing com.google.j2objc:j2objc-annotations:1.3
:providing org.ow2.asm:asm-util:8.0
:providing com.google.code.findbugs:jsr305:3.0.2
:providing org.ow2.asm:asm:8.0
:providing org.ow2.asm:asm-analysis:8.0
:providing com.google.guava:guava:28.0-jre
:providing io.github.minecraft-cursed-legacy:cursed-legacy-api:1.1.0.1
:providing org.apache.logging.log4j:log4j-api:2.8.1
:providing org.ow2.asm:asm-commons:8.0
:providing valoeghese:ZoesteriaConfig:1.3.6
:providing org.apache.logging.log4j:log4j-core:2.8.1
:providing org.codehaus.mojo:animal-sniffer-annotations:1.17
:providing com.google.guava:failureaccess:1.0.1
:providing com.google.code.gson:gson:2.8.6
:setting up mappings (io.github.minecraft-cursed-legacy.plasma build.18@b1.7.3)
:providing com.github.paulevsGitch:B.1.7.3-CoreLib:v.1.3.0 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:cursed-legacy-api:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-networking-v0:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-commands-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-lifecycle-events-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-terrain-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-attached-data-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-registries-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-tile-entities-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-worldtypes-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy:cursed-fabric-loader:1.0.0 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-recipes-v0:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-translations-v0:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-api-base:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-config-v0:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-textures-v1:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)
:providing io.github.minecraft-cursed-legacy.cursed-legacy-api:legacy-interaction-events-v0:1.1.0.1 (io.github.minecraft-cursed-legacy.plasma.b1_7_3.build.18)

> Task :genSources
Error thrown whilst in com/jcraft/jorbis/Floor1
Method inverse1 (Lcom/jcraft/jorbis/Block;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class com/jcraft/jorbis/Floor1 couldn't be decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.modules.decompiler.exps.FunctionExprent.checkExprTypeBounds(FunctionExprent.java:386)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:139)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:124)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.checkTypeExprent(VarTypeProcessor.java:124)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.lambda$processVarTypes$1(VarTypeProcessor.java:118)
        at org.jetbrains.java.decompiler.modules.decompiler.sforms.DirectGraph.iterateExprents(DirectGraph.java:98)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.processVarTypes(VarTypeProcessor.java:118)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarTypeProcessor.calculateVarTypes(VarTypeProcessor.java:44)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarVersionsProcessor.setVarVersions(VarVersionsProcessor.java:44)
        at org.jetbrains.java.decompiler.modules.decompiler.vars.VarProcessor.setVarVersions(VarProcessor.java:37)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:149)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:61)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:472)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:388)
        at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:148)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Error thrown whilst in net/minecraft/client/Minecraft
Method method_2130 (Ljava/lang/String;)V in class net/minecraft/client/Minecraft couldn't be decompiled.
java.lang.NullPointerException
        at org.jetbrains.java.decompiler.util.VBStyleCollection.removeWithKey(VBStyleCollection.java:88)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractIfBlock(LoopExtractHelper.java:197)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractFirstIf(LoopExtractHelper.java:160)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoop(LoopExtractHelper.java:85)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:54)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoopsRec(LoopExtractHelper.java:39)
        at org.jetbrains.java.decompiler.modules.decompiler.LoopExtractHelper.extractLoops(LoopExtractHelper.java:20)
        at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:167)
        at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:61)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:472)
        at org.jetbrains.java.decompiler.main.ClassesProcessor.processClass(ClassesProcessor.java:388)
        at org.jetbrains.java.decompiler.main.Fernflower.processClass(Fernflower.java:148)
        at org.jetbrains.java.decompiler.struct.ContextUnit.lambda$save$2(ContextUnit.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

> Task :genSources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':genSources'.
> java.nio.file.AtomicMoveNotSupportedException: D:\Downloads\legacy-fabric-test-mod\build\tmp\genSources\line-mapped.jar -> C:\Users\admin\.gradle\caches\fabric-loom\minecraft-b1.7.3-mapped-io.github.minecraft-cursed-legacy.plasma-build.18.jar: The system cannot move the file to a different disk drive.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
2 actionable tasks: 2 executed
```
